name: "image_enhancer"
backend: "onnxruntime"
max_batch_size: 8

input [
  {
    name: "input_image"
    data_type: TYPE_FP32
    dims: [3, -1, -1]
  }
]

output [
  {
    name: "output_image"
    data_type: TYPE_FP32
    dims: [3, -1, -1]
  }
]

dynamic_batching {
  preferred_batch_size: [1, 2, 4, 8]
  max_queue_delay_microseconds: 100
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

optimization {
  execution_accelerators {
    gpu_execution_accelerator : [
      {
        name : "tensorrt"
        parameters { key: "precision_mode" value: "FP16" }
      }
    ]
  }
}
